### ISSUE TITLE
Sub-schema for Avro::Schema::UnionSchema not a valid Avro schema

### ISSUE THREAD

**Issue by seanhandley** [salsify/avromatic#90]
Avromatic version `0.32.0`

## Generating the avsc

We're using Avromatic to load `.avsc` files generated by

```
avro-tools idl2schemata
```

The avro-tools version is `1.8.2`.

## The Avromatic error

The error and stack trace from Avromatic are:

```
Gem Load Error is: Sub-schema for Avro::Schema::UnionSchema not a valid Avro schema. Bad schema: {"type"=>"record", "name"=>"JobCreated", "doc"=>"* Represents the fact that a new job has been created in the platform and that\n     * the system will start looking for drivers to fulfill that job whenever\n     * possible (See ScheduledJob)", "fields"=>[{"name"=>"job_id", "type"=>"int"}, {"name"=>"client_id", "type"=>"int"}, {"name"=>"deliveries", "type"=>{"type"=>"array", "items"=>{"type"=>"record", "name"=>"Delivery", "doc"=>"* Represents a Delivery being the concept of bringing package X from point A to\n     * point B", "fields"=>[{"name"=>"delivery_id", "type"=>"int"}, {"name"=>"pickup", "type"=>{"type"=>"record", "name"=>"Location", "doc"=>"* Describes a point in a map", "fields"=>[{"name"=>"latitude", "type"=>"double"}, {"name"=>"longitude", "type"=>"double"}]}}, {"name"=>"dropoff", "type"=>"Location"}, {"name"=>"package_type", "type"=>{"type"=>"enum", "name"=>"PackageType", "doc"=>"* The set of standarized sizes for packages", "symbols"=>["SIZE_UNKNOWN", "XSMALL", "SMALL", "MEDIUM", "LARGE", "XLARGE"]}}, {"name"=>"time_constraints", "type"=>{"type"=>"array", "items"=>{"type"=>"record", "name"=>"TimeConstraint", "doc"=>"* Represents a time constraint on a delivery action", "fields"=>[{"name"=>"action", "type"=>{"type"=>"enum", "name"=>"DeliveryAction", "doc"=>"* The set of available actions for a delivery", "symbols"=>["PICKUP", "DROPOFF"]}}, {"name"=>"time_window", "type"=>{"type"=>"record", "name"=>"TimeWindow", "doc"=>"* Describes a time window closed at the beginning and open at the end \"[from, to[\"", "fields"=>[{"name"=>"from", "type"=>{"type"=>"long", "logicalType"=>"timestamp-millis"}}, {"name"=>"to", "type"=>{"type"=>"long", "logicalType"=>"timestamp-millis"}}]}}]}}}]}}}, {"name"=>"requested_transport", "type"=>["null", {"type"=>"enum", "name"=>"TransportType", "doc"=>"* The set of available Transport Types", "symbols"=>["WALK", "BIKE", "MOTORBIKE", "CAR", "CARGOBIKE", "VAN", "CARGOBIKEXL", "MOTORBIKEXL", "STEERWAGON"]}]}, {"name"=>"priority", "type"=>"int", "default"=>0}, {"name"=>"fleets", "type"=>["null", {"type"=>"array", "items"=>"int"}], "default"=>nil}]}
Backtrace for gem load error is:
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:170:in `rescue in subparse'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:166:in `subparse'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/schema_compatibility/schema.rb:36:in `block in initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/schema_compatibility/schema.rb:35:in `each'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/schema_compatibility/schema.rb:35:in `each_with_object'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/schema_compatibility/schema.rb:35:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/logical_types/schema.rb:49:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/logical_types/schema.rb:49:in `real_parse'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:167:in `subparse'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:367:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro_turf-0.8.1/lib/avro_turf/schema_to_avro_patch.rb:27:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/default_validation/schema.rb:5:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:216:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:216:in `block in make_field_objects'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:210:in `each'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:210:in `each_with_index'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-1.8.2/lib/avro/schema.rb:210:in `make_field_objects'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro_turf-0.8.1/lib/avro_turf/schema_to_avro_patch.rb:14:in `make_field_objects'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/schema_compatibility/schema.rb:24:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/logical_types/schema.rb:33:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro-patches-0.4.0/lib/avro-patches/logical_types/schema.rb:33:in `real_parse'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avro_turf-0.8.1/lib/avro_turf/schema_store.rb:21:in `find'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/configuration.rb:48:in `find_schema_by_option'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/configuration.rb:42:in `find_avro_schema'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/configuration.rb:25:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:39:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:39:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:27:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:27:in `block in model'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:26:in `initialize'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:26:in `new'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model/builder.rb:26:in `model'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/avromatic-0.32.0/lib/avromatic/model.rb:48:in `model'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/business_events-1.8.0/lib/business_events/events.rb:2:in `<module:BusinessEvent>'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/business_events-1.8.0/lib/business_events/events.rb:1:in `<main>'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/business_events-1.8.0/lib/business_events.rb:4:in `<main>'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/sean/src/stuart/stuart-api/config/application.rb:8:in `<top (required)>'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/sean/.rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
```

## Summary

This started happening after we introduced the following union type in the avdl.

```
union { null, array<int> } fleets = null;
```

which seems to generate the corresponding avsc:

```
{"name"=>"fleets", "type"=>["null", {"type"=>"array", "items"=>"int"}], "default"=>nil}
```

We're pretty stumped as to why Avromatic would fail to validate this. The generated `avsc` is being used by our Scala-based toolset without any issues.

Is this something you've seen before? Any ideas what the root of the problem could be?

**Comment by jturkel** [comment]
It looks like this might be a bug in the Avro Ruby library. Do you get the same error if you attempt to parse the generated schema via `Avro::Schema.parse(<schema string>)`?

**Comment by seanhandley** [comment]
No, it works fine:

```
pry(main)> Avro::Schema.parse(s)
=> #<Avro::Schema::RecordSchema:0x00007fc568de3430
 @fields=
  [#<Avro::Schema::Field:0x00007fc568de2c60
    @default=:no_default,
    @name="created_at",
    @order=nil,
    @type=#<Avro::Schema::PrimitiveSchema:0x00007fc568de2c38 @logical_type="timestamp-millis", @type_sym=:long>>,
   #<Avro::Schema::Field:0x00007fc568de2bc0
    @default=:no_default,
    @name="msg",
    @order=nil,
    @type=
     #<Avro::Schema::UnionSchema:0x00007fc568de2b98
      @logical_type=nil,
      @schemas=
       [#<Avro::Schema::RecordSchema:0x00007fc568de2af8
         @fields=
          [#<Avro::Schema::Field:0x00007fc568de24e0
            @default=:no_default,
...
```

**Comment by jturkel** [comment]
If you create a reproducible test case I'd be happy to take a look.

**Comment by seanhandley** [comment]
Thanks @jturkel - we ended up working around the issue due to commercial pressures to get a working solution.

I will set up a reproducible test repo when I can.

**Comment by jturkel** [comment]
@seanhandley - I'm closing this issue due to lack of activity but feel free to reopen this with a reproducible test case if it's still a problem.

**Comment by nishantgupta204** [comment]
Hi,

I am getting the same issue. On analysing it I found that Avro.Schema.Parse(string) is causing the issue. Avro.Schema.Parse is adding a type attribute in front of my schema making my shema invalid. Please help us to resolve the issue

**Comment by jturkel** [comment]
@nishantgupta204 - Do you have a reproducible test case? Is the problem with the avromatic gem or the avro gem?
